services:
  frontend:
    container_name: ninjinji-font-app
    image: frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
  backend:
    container_name: ninjinji-api-app
    image: backend
    restart: unless-stopped
    ports:
      - "8000:8000"

  db:
    container_name: ninjinji-db
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

    volumes:
      - postgres-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
      - "10000:8080"
    environment:
      - ADMINER_DESIGN=pepa-linha
    restart: unless-stopped

  plc:
    container_name: plc-app
    image: plc
    ports:
      - "9000:9000"
    restart: unless-stopped

  # 注意，每次重构的时候，都要把数据库里的	alembic_version	表清空一下，才能成功build
  # app:
  #   container_name: ninjinji-font-app
  #   image: ninjinji-font
  #   build:
  #     context: .
  #   # command: reflex db init && reflex db migrate && reflex run
  #   ports:
  #     - "3000:3000"
  #     - "8000:8000"
  #   restart: unless-stopped

volumes:
  postgres-data:

    # networks:
    #   ninjinji-network:
    #     external: true
