# build line
FROM python:3.11

# FROM opcua-middleware
ENV PYTHONUNBUFFERED 1

WORKDIR /app

COPY ./plc .

# build line
# RUN pip install --upgrade pip --proxy="http://10.30.24.88:7890" && pip install fastapi uvicorn[standard] opcua websockets  --proxy="http://10.30.24.88:7890" --no-cache
RUN pip install --upgrade pip --proxy="http://10.30.24.88:7890" && pip install -r requirements.txt  --proxy="http://10.30.24.88:7890" --no-cache

CMD python app.py