"""empty message

Revision ID: 32300ab435bc
Revises: 
Create Date: 2025-01-09 09:54:08.101106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '32300ab435bc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operatorlogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('worker_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('worker_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('class_group', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('operation_time', sa.DateTime(), nullable=False),
    sa.Column('operation_year', sa.Integer(), nullable=False),
    sa.Column('operation_month', sa.Integer(), nullable=False),
    sa.Column('operation_day', sa.Integer(), nullable=False),
    sa.Column('operation_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('operation_content', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('operation_result', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('operatorlogs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_operatorlogs_operation_time'), ['operation_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_operatorlogs_worker_id'), ['worker_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_operatorlogs_worker_name'), ['worker_name'], unique=False)

    op.create_table('system',
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('create_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('version')
    )
    with op.batch_alter_table('system', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_create_at'), ['create_at'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('worker_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('class_group', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('face_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('worker_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    with op.batch_alter_table('system', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_create_at'))

    op.drop_table('system')
    with op.batch_alter_table('operatorlogs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_operatorlogs_worker_name'))
        batch_op.drop_index(batch_op.f('ix_operatorlogs_worker_id'))
        batch_op.drop_index(batch_op.f('ix_operatorlogs_operation_time'))

    op.drop_table('operatorlogs')
    # ### end Alembic commands ###
