[plc]
host = "192.168.10.10:4840"

[nodes]
[nodes.node-heartbeat]
node_id = "ns=4;i=17"

[nodes.node-jog-add]
node_id = "ns=4;i=20"

[nodes.node-jog-sub]
node_id = "ns=4;i=21"

[nodes.reset]
node_id = "ns=4;i=22"

[nodes.node-start]
node_id = "ns=4;i=18"

[nodes.node-stop]
node_id = "ns=4;i=19"

[nodes.torque-value]             # mes.torque_value
node_id = "ns=4;i=23"

[nodes.aim-torque]
node_id = "ns=4;i=27"

[nodes.max-torque]
node_id = "ns=4;i=26"

[nodes.output-torque]
node_id = "ns=4;i=28"

[nodes.handle-mode]
node_id = "ns=4;i=25"

[nodes.act-torque]
node_id = "ns=4;i=30"

[nodes.torque-measure-value]
node_id = "ns=4;i=29"

[nodes.torque-current-set-value]
node_id = "ns=4;i=31"

[nodes.torque-set-output]
node_id = "ns=4;i=32"

[nodes.torque-feedback]
node_id = "ns=4;i=33"