import reflex as rx
from .state import AdminState


def add_customer():
    return rx.dialog.root(
        rx.dialog.trigger(
            rx.button(
                rx.flex(
                    "新增用户",
                    rx.icon(tag="plus", width=20, height=20),
                    spacing="3",
                ),
                size="3",
                radius="full",
            ),
        ),
        rx.dialog.content(
            rx.dialog.title(
                "新增用户",
                font_family="Inter",
            ),
            rx.dialog.description(
                "填写用户信息",
                size="2",
                mb="4",
                padding_bottom="1em",
            ),
            rx.flex(
                rx.text(
                    "姓名",
                    as_="div",
                    size="2",
                    mb="1",
                    weight="bold",
                ),
                rx.input(
                    placeholder="姓名",
                    on_blur=AdminState.set_name_field,
                    on_change=AdminState.set_name_field,
                ),
                rx.text(
                    "工号",
                    as_="div",
                    size="2",
                    mb="1",
                    weight="bold",
                ),
                rx.input(
                    placeholder="工号",
                    on_blur=AdminState.set_worker_id_field,
                    on_change=AdminState.set_worker_id_field,
                ),
                rx.text(
                    "班组",
                    as_="div",
                    size="2",
                    mb="1",
                    weight="bold",
                ),
                rx.input(
                    placeholder="班组",
                    on_blur=AdminState.set_class_group_field,
                    on_change=AdminState.set_class_group_field,
                ),
                rx.text(
                    "密码",
                    as_="div",
                    size="2",
                    mb="1",
                    weight="bold",
                ),
                rx.input(
                    placeholder="密码",
                    type="password",
                    on_blur=AdminState.set_password_field,
                    on_change=AdminState.set_password_field,
                ),
                direction="column",
                spacing="3",
            ),
            rx.flex(
                rx.dialog.close(
                    rx.button(
                        "取消",
                        variant="soft",
                        color_scheme="gray",
                    ),
                ),
                rx.dialog.close(
                    rx.button(
                        "新增",
                        on_click=AdminState.add_User,
                        variant="solid",
                    ),
                ),
                padding_top="1em",
                spacing="3",
                mt="4",
                justify="end",
            ),
            style={"max_width": 450},
            box_shadow="lg",
            padding="1em",
            border_radius="25px",
            font_family="Inter",
        ),
    )

